/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./components/Appbar.vue')['default']
    Clock: typeof import('./components/widgets/Clock.vue')['default']
    GGRBK: typeof import('./components/widgets/GGRBK.vue')['default']
    Quote: typeof import('./components/widgets/Quote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StopWatch: typeof import('./components/widgets/StopWatch.vue')['default']
    Timer: typeof import('./components/widgets/Timer.vue')['default']
    Weather: typeof import('./components/widgets/Weather.vue')['default']
    Widget: typeof import('./components/Widget.vue')['default']
  }
}
